build:
	gcc -L /opt/homebrew/Cellar/sdl2/2.0.22/lib -I /opt/homebrew/Cellar/sdl2/2.0.22/include -I /opt/homebrew/Cellar/sdl2/2.0.22/include/sdl2 -I /opt/homebrew/Cellar/sdl2_ttf/2.20.0/include -c SDL_FontCache.c -o SDL_FontCache.o
	emcc -c SDL_FontCache.c -o SDL_FontCache.emsc.o