template<> constexpr unsigned int getID<PositionComponent>() { return 0; }
template<> constexpr unsigned int getID<SizeComponent>() { return 1; }
template<> constexpr unsigned int getID<RenderComponent>() { return 2; }
template<> constexpr unsigned int getID<HealthComponent>() { return 3; }
template<> constexpr unsigned int getID<GrowthComponent>() { return 4; }
template<> constexpr unsigned int getID<CenteredRenderFlagComponent>() { return 5; }
template<> constexpr unsigned int getID<ExplosionComponent>() { return 6; }
template<> constexpr unsigned int getID<NametagComponent>() { return 7; }
template<> constexpr unsigned int getID<ExplosiveComponent>() { return 8; }
template<> constexpr unsigned int getID<InventoryComponent>() { return 9; }
template<> constexpr unsigned int getID<MotionComponent>() { return 10; }
template<> constexpr unsigned int getID<DyingComponent>() { return 11; }
template<> constexpr unsigned int getID<InserterComponent>() { return 12; }
template<> constexpr unsigned int getID<RotationComponent>() { return 13; }
template<> constexpr unsigned int getID<RotatableComponent>() { return 14; }
template<> constexpr unsigned int getID<FollowComponent>() { return 15; }
template<> constexpr unsigned int getID<ImmortalEC>() { return 16; }
template<> constexpr unsigned int getID<AngleMotionEC>() { return 17; }
template<> constexpr unsigned int getID<ItemStackComponent>() { return 18; }
